interacts('lidocaine_viscous', 'r_a_acne').
interacts(erygel, 'duaklir_pressair').
interacts(alamag, celecoxib).
interacts('theraflu_warming_relief_nighttime_severe_cold_&_cough', zinacef).
interacts(mydayis, 'sudafed_pe_severe_cold').
interacts('amitriptyline_/_perphenazine', 'doravirine_/_lamivudine_/_tenofovir').
interacts(unasyn, 'np_thyroid').
interacts(captopril, phenytoin).
interacts(prolate, orlistat).
interacts('regenecare_ha_spray', alteplase).
interacts(acanya, 'methadone_diskets').
interacts('oxtellar_xr', ethosuximide).
interacts(fortabs, dolono).
interacts(sprix, marplan).
interacts('coditussin_dac', iloperidone).
interacts(alfentanil, 'emcin_clear').
interacts(lamivudine, byetta).
interacts(mecamylamine, actiq).
interacts('coricidin_hbp_maximum_strength_flu', ecpirin).
interacts('allergy_relief_tablets', humira).
interacts(vytone, toviaz).
interacts(atorvastatin, 'benazepril_/_hydrochlorothiazide').
interacts('tums_smoothies', aclasta).
interacts(covaryx, pyridoxine).
interacts(fibricor, 'itch-x_lotion').
interacts('chlorex_a', brexpiprazole).
interacts('hydrochlorothiazide_/_valsartan', 'ambien_cr').
interacts('aspirin_/_butalbital_/_caffeine', 'hydrochlorothiazide_/_lisinopril').
interacts(gastrocrom, singulair).
interacts(viloxazine, dytan-dm).
interacts(zegerid, 'actoplus_met').
interacts(winlevi, clemastine).
interacts(menthol, 'clarinex-d_24_hour').
interacts('aciphex_sprinkle', 'ultralytic_2').
interacts(euflexxa, 'tranxene_t-tab').
interacts(vocabria, 'inova_8/2').
interacts(dyclonine, baciim).
interacts('astramorph_pf', emsam).
interacts('a-g_profen', 'delsym_cough_&_sore_throat').
interacts(myxredlin, aptiom).

safe(X, Y) :- \+ interacts(X, Y), \+ interacts(Y, X).
